package frontend.soap;

import frontend.objects.*;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

import java.net.URL;

public class SoapClient {

	public static void main(String[] args) {

        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();        

        // Use the URL defined in the soap address portion of the WSDL
        factory.setAddress("http://localhost:8080/CD_Project/services/SoapServicesImpPort"); 
       
        // Utilize the class which was auto-generated by Apache CXF wsdl2java
        factory.setServiceClass(SoapServices.class);        

        SoapServices client = (SoapServices) factory.create();

        try {        
        	
        	Message test = new Message("adasd","adas");
    
            // Call the Web Service to perform an operation
            Message response = ((SoapServices)client).ReserveShadow(test);
        
            System.out.println(response.getContent());    
        
          } catch (SecurityException e) {

            e.printStackTrace();

          } catch (IllegalArgumentException e) {

            e.printStackTrace();

          }        
	}
}
