
package frontend.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Sun Dec 17 19:07:55 WET 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "AddIntegers", namespace = "http://soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddIntegers", namespace = "http://soap.frontend/", propOrder = {"a", "b"})

public class AddIntegers {

    @XmlElement(name = "a")
    private int a;
    @XmlElement(name = "b")
    private int b;

    public int getA() {
        return this.a;
    }

    public void setA(int newA)  {
        this.a = newA;
    }

    public int getB() {
        return this.b;
    }

    public void setB(int newB)  {
        this.b = newB;
    }

}

