
package frontend.Soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Sun Dec 17 12:18:42 GMT 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "addIntegers", namespace = "http://Soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addIntegers", namespace = "http://Soap.frontend/", propOrder = {"arg0", "arg1"})

public class AddIntegers {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private int arg1;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

}

