
package frontend.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Fri Dec 15 09:28:13 GMT 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "GetBeachServicesResponse", namespace = "http://soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBeachServicesResponse", namespace = "http://soap.frontend/")

public class GetBeachServicesResponse {

    @XmlElement(name = "return")
    private frontend.objects.ReturnBeachService _return;

    public frontend.objects.ReturnBeachService getReturn() {
        return this._return;
    }

    public void setReturn(frontend.objects.ReturnBeachService new_return)  {
        this._return = new_return;
    }

}