
package frontend.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Mon Jan 01 21:12:20 WET 2024
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "registarUtilizador", namespace = "http://soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registarUtilizador", namespace = "http://soap.frontend/")

public class RegistarUtilizador {

    @XmlElement(name = "arg0")
    private objects.User arg0;

    public objects.User getArg0() {
        return this.arg0;
    }

    public void setArg0(objects.User newArg0)  {
        this.arg0 = newArg0;
    }

}

