
package frontend.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Wed Dec 20 17:17:00 WET 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "reservarSombrinha", namespace = "http://soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reservarSombrinha", namespace = "http://soap.frontend/")

public class ReservarSombrinha {

    @XmlElement(name = "arg0")
    private objects.Booking arg0;

    public objects.Booking getArg0() {
        return this.arg0;
    }

    public void setArg0(objects.Booking newArg0)  {
        this.arg0 = newArg0;
    }

}
