
package frontend.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Wed Dec 20 17:17:00 WET 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "ReserveShadowResponse", namespace = "http://soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReserveShadowResponse", namespace = "http://soap.frontend/")

public class ReserveShadowResponse {

    @XmlElement(name = "return")
    private frontend.objects.Message _return;

    public frontend.objects.Message getReturn() {
        return this._return;
    }

    public void setReturn(frontend.objects.Message new_return)  {
        this._return = new_return;
    }

}

