
package frontend.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Tue Dec 05 21:56:25 GMT 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "SendData", namespace = "http://soap.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SendData", namespace = "http://soap.frontend/")

public class SendData {

    @XmlElement(name = "arg0")
    private frontend.objects.Message arg0;

    public frontend.objects.Message getArg0() {
        return this.arg0;
    }

    public void setArg0(frontend.objects.Message newArg0)  {
        this.arg0 = newArg0;
    }

}