
package frontend.Rest.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Fri Dec 15 09:28:13 GMT 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "GetBeachServices", namespace = "http://Rest.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBeachServices", namespace = "http://Rest.frontend/")

public class GetBeachServices {


}

