
package frontend.Rest.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Tue Dec 05 15:14:59 GMT 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "GetMessaegContent", namespace = "http://Rest.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetMessaegContent", namespace = "http://Rest.frontend/")

public class GetMessaegContent {


}

