
package frontend.Rest.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.6.2
 * Tue Dec 26 15:01:44 GMT 2023
 * Generated source version: 3.6.2
 */

@XmlRootElement(name = "ReserveShadow", namespace = "http://Rest.frontend/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReserveShadow", namespace = "http://Rest.frontend/")

public class ReserveShadow {

    @XmlElement(name = "arg0")
    private frontend.Rest.ReserveShadowContent arg0;

    public frontend.Rest.ReserveShadowContent getArg0() {
        return this.arg0;
    }

    public void setArg0(frontend.Rest.ReserveShadowContent newArg0)  {
        this.arg0 = newArg0;
    }

}

